path_to_iemocap='D:/IEMOCAP/'
path_to_chinese_dataset='C:/Users/wangzi/Desktop/大创资料/语料库/chinese_dataset/'
path_to_sentences_samples = 'D:/IEMOCAP/sentences_csv/'
path_to_dialog_samples = 'D:/IEMOCAP/dialog_csv/'
path_to_chinese_samples = 'D:/IEMOCAP/chinese_csv/'
available_emotions = ['ang','neu','sad' ] #'fea', 'hap' ,'fea', 'hap' , 'sur' 'neu'
#available_emotions = ['ang', 'neu','sad','exc','fru']#,'hap','exc','sur','fru'
data_type=0 #{'iemocap_sentences':1,'chinese_dataset':0}
get_data=0 #是否重新读取音频样本
get_features=0 #是否重新提取特征